name: 'Java Pipeline'

on:
  workflow_call:
    inputs: 
      java_version:
        type: string
        description: 'Java version to be used'
        required: true

jobs:
  pipeline:
    name: Pipeline
    uses: GitHub-Accelerate/GH-Intermediate-Workflows/.github/workflows/vault.yml@main
    secrets: inherit

  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: |
          echo "Hi everyone."
