name: 'Java Pipeline'

on:
  workflow_call:
    inputs: 
      java_version:
        type: string
        description: 'Java version to be used'
        required: true

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v4

      - name: Test
        run: |
          echo "Hi everyone."
