name: 'Java Pipeline'

permissions:
  actions: write       # Necessary to cancel workflow executions
  checks: write        # Necessary to write reports
  pull-requests: write # Necessary to comment on PRs
  contents: read
  packages: write

on:
  workflow_call:
    inputs: 
      java_version:
        type: string
        description: 'Java version to be used'
        required: true

jobs:
  pipeline:
    name: Pipeline
    uses: GitHub-Accelerate/GH-Intermediate-Workflows/.github/workflows/vault.yml@main
    secrets: inherit

  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v4

      - name: Test
        run: |
          echo "Hi everyone."
