name: 'Java Pipeline'

on:
  workflow_call:
    inputs: 
      java-version:
        type: string
        description: 'Java version to be used'
        required: true

jobs:
  pipeline:
    name: Pipeline
    uses: GitHub-Accelerate/GH-Intermediate-Workflows/.github/workflows/vault.yml@main
    secrets: inherit

  sonarqube:
    name: SonarQube
    uses: GitHub-Accelerate/GH-Intermediate-Workflows/.github/workflows/sonarqube.yml@main
    secrets: inherit

  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
